# Generated by Django 4.1.2 on 2022-10-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
