# Generated by Django 4.1.2 on 2022-10-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_dob_account_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(max_length=2500, null=True, upload_to=''),
        ),
    ]
