# Generated by Django 4.1.2 on 2022-10-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateField()),
                ('image', models.ImageField(max_length=2500, upload_to='')),
            ],
        ),
    ]
