# Generated by Django 4.1.2 on 2022-10-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
